
EMAIL_USER = "ndianabernard@yahoo.com"
EMAIL_PASS = "ckohtpbfrevtuhcy"
EMAIL_PROVIDER = "Yahoo Mail"
imap_server = "imap.mail.yahoo.com"
USERNAME = "Ndiana"
PASSWORD_HASH = "scrypt:32768:8:1$ZuqIvA0iQU9JXsO3$923bc8372e68553abe59ef2dc0b978255bedb675d707038cb410be42376414fe582675d0a20293864f71521f47e34a952ad444703092304c6804dd38a5283e27"

["openai"]
"api_key" = "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"